[package]
name = "quickreplace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-colorizer = "1"
regex = "1"
# 1만 작성하고 하위 버전을 작성하지 않으면 1.x.x 형태의 해당 버전에서 최신 업데이트를 가져온다.